Improve draft blocker message

diff --git a/.forgejo/workflows/block-drafts.yml b/.forgejo/workflows/block-drafts.yml
--- a/.forgejo/workflows/block-drafts.yml
+++ b/.forgejo/workflows/block-drafts.yml
@@ -9,5 +9,8 @@ jobs:
         uses: https://code.forgejo.org/actions/checkout@v4
       - name: block-drafts
         run: |
-          if make find-drafts ; then echo "Failure: found drafts"; exit 1; fi
+          if make find-drafts ; then
+            echo "Failure: can't merge draft posts into main. See list of relevant files above."
+            exit 1
+          fi
           echo "Success!"
